### PR TITLE
Handle exception when running rspec (Queue mode) 

### PR DESCRIPTION
**Pull request by thukim**
Issue: When running rspec with the queue mode and having exception, the existing code doesn't trigger the `after_subset_queue` and `after_queue` hooks 

This PR handles exception in the above scenario that:
- It logs the exception which causes Knapsack Pro to exit/abort (debug mode)
- Triggers the `after_subset_queue` and `after_queue`
- Prints the summary before exiting: Unexecuted tests, pending tests and failed tests
After that, it will re-raise the exception.

Please let me know if there is anything I need to update/address in this PR. Thank you!

### CODE REVIEW

**Comment by ArturT** [comment]
Thanks for the PR, @thukim 

Could you resolve the conflicts with the master branch?

My [PR](https://github.com/KnapsackPro/knapsack_pro-ruby/pull/207/files) introduced small changes to the files:

* `lib/knapsack_pro/runners/queue/rspec_runner.rb`
* `spec/knapsack_pro/runners/queue/rspec_runner_spec.rb`

or you can give us access to the PR and we can do it on our own when we will start review for this PR. Thanks.

To do it, edit PR and select `Allow edits from maintainers`. [More info](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork). Thank you.

**Comment by thukim** [comment]
Hi @ArturT ,

I have resolved conflict and also selected `Allow edits by maintainers` to give you access to the PR.

Thanks!

**Comment by ArturT** [comment]
Thanks @thukim

**Review by ArturT — APPROVED** [review]

**Comment by ArturT** [comment]
I added some small improvements on top of this PR.

* https://github.com/KnapsackPro/knapsack_pro-ruby/pull/215

**Pull request merged**
